spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:blog}
spring.datasource.password=${DB_PASSWORD:}
